## counts_links table definition
---
name: appointments
primarykey: id
engine: InnoDB
charset: utf8
autoincrement:
    colname: id
    start: 1
cols:
    id:
        type: bigint
        length: 20
        params: NOT NULL
    description:
        type: varchar
        length: 255
        params: NOT NULL
    datetime:
        type: bigint
        length: 20
        params: NOT NULL
    pending:
        type: bool
        length: 1
        params: NOT NULL
    visible:
        type: bool
        length: 1
        params: NOT NULL
    createtime:
        type: bigint
        length: 20
        params: NOT NULL
    createuser:
        type: bigint
        length: 20
        params: NOT NULL
indices:
    app_descr_time_pendig:
        col:
            description
            datetime
            pending
        isUnqiue: true
defaultvalues:
    rows:
